export const ADD_GAME = 'ADD_GAME';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_ERROR = 'ADD_GAME_ERROR';
export const CHANGE_WHITE_PLAYER = 'CHANGE_WHITE_PLAYER';
export const CHANGE_BLACK_PLAYER = 'CHANGE_BLACK_PLAYER';
export const CHANGE_WINNER = 'CHANGE_WINNER';
